language: python
python:
  - "3.6"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo StoriesAppServer --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
install:
  - pip install -r requirements.txt
script:
  - python tests.py
