version: '2'
services:
  mongo:
    image: mongo:3.6-jessie
    ports:
      - "27017:27017"
    networks:
      - my-net
  web-api:
    build: .
    ports:
     - "5000:5000"
     - "8000:8000"
    networks:
     - my-net
    depends_on:
     - mongo
networks:
  my-net:
    driver: bridge   
