codeMap = {
"MOCK01": "MOCK: Signup parameters missing",
"MOCK02": "MOCK: User %1$ already registered",
"MOCK03": "MOCK: Incorrect login information",
"MOCK04": "MOCK: User %1$ not registered",
"FLASH01": "FlashStories: Story does not exist",
"STORIES01": "Non existing story",
"LOGINUSERS01": "Failed to login user %1$",
"AUTHSERVER01": "Falied to authenticate server %1$",
"API00":"",
"API01":"[userSignUpController.authenticateSignUp]Error at sign up. Response message received: %1$",
"API02":"[usersLoginController.validateUserLogin]Request header is missing token and password",
"API03":"[usersLoginController.validateUserLogin]Error: %1$",
"API04":"[peopleController.searchForPerson]Request header is missing searched users",
"API05":"[peopleController.searchForSinglePerson]Request header is missing searched user",
"API06":"[invitationsController.getUserInvitations]Request header is missing username",
"API07":"[invitationsController.getUserInvitations]No invitations found for user %1$",
"API08":"[invitationsController.addFriendInvitation]Request header is missing username",
"API09":"[invitationsController.addFriendInvitation]Request header is missing friend name",
"API10":"[invitationsController.acceptFriendInvitation]Request header is missing username",
"API11":"[invitationsController.acceptFriendInvitation]Request header is missing friend name",
"API12":"[invitationsController.]Error when accepting invitation between %1$ and %2$",
"API13":"[friendsController.getUserFriends]Request header is missing username",
"API14":"[friendsController.addFriend]Request header is missing username/friend",
"API14b":"[friendsController.removeFriend]Request header is missing username",
"API15":"[friendsController.removeFriend]Request header is missing friend",
"API16":"[friendsController.getSpecificUserFriends]Request header is missing username",
"API17":"[friendsController.getSpecificUserFriends]User not registered or has no friends",
"API18":"[notificationsController.getUserNotifications]Request header is missing user",
"API19":"[profilesController.getUserProfile]Request header missing username",
"API20":"[profilesController.updateUserProfile]Request header missing username",
"API21":"[storiesController.getHomepageFeed]Request header is missing username",
"API22":"[storiesController.addNewStory]Request header is missing username",
"API23":"[storiesController.updateStory]Request header is missing story ID",
"API24":"[storiesController.removeStory]Request header is missing username",
"API25":"[friendsController.removeFriend]Friend not in users friend list",
"API26":"[friendsController.addFriend]Error found while adding friend",
"API27":"[reactionsController.addNewReaction]Request header is missing story ID",
"API28":"[reactionsController.addNewReaction]Request header is missing username",
"API29":"[reactionsController.addNewReaction]Request header is missing reaction",
"API30":"[reactionsController.removeReaction]Request header is missing story ID",
"API31":"[reactionsController.removeReaction]Request header is missing username",
"API32":"[commentsController.getStoryComments]Request header is missing information",
"API33":"[commentsController.addNewComment]Request header is missing storyID",
"API34":"[commentsController.addNewComment]Request header is missing username",
"API35":"[commentsController.addNewComment]Request header is missing comment",
"API36":"[commentsController.removeComment]Request header is missing story ID",
"API37":"[commentsController.removeComment]Request header is missing comment ID",
"API38":"[conversationsController.getUserConversations]Request header is missing username",
"API39":"[conversationsController.createNewConversations]Request header is missing first user",
"API40":"[conversationsController.createNewConversations]Request header is missing second user",
"API41":"[userSignUpController.authenticateSignUp]Error found. Response message received: %1$",
"API42":"[reactionsController.getStoryReactions]Request header is missing story ID",
"API43":"[storiesController.updateStory]Cant modify vital metadata from a multimeda file. URL=%1$",
"API44":"[statsController.authenticateServer] No server found with id %1$",
"API45":"[statsController.authenticateServer] Server id is incorrect",
"API46":"[flashStoriesController.getHomepageFeed] Request header is missing username",
"API47":"[flashStoriesController.addNewStory] Request header is missing username",
"API48":"[flashStoriesController.updateStory] Request header is missing username",
"API49":"[flashStoriesController.updateStory]Cant modify vital metadata from a multimeda file. URL=%1$",
"API50":"[flashStoriesController.removeStory]Request header is missing username	",
"API51":"[flashStoriesController.getHomepageFeed] Error obtaining flash story url %1$",
"API52":"[flashStoriesController.addNewStory] Error uploading flash story"
}
